extra_header: |
  // OPCUA for Rust
  // SPDX-License-Identifier: MPL-2.0
  // Copyright (C) 2017-2024 Adam Lock, Einar Omang
targets:
  - type: types
    file: Opc.Ua.NodeSet2.Services.xml
    output_dir: async-opcua-types/src/generated/types
    enums_single_file: true
    types_import_map:
      Argument:
        path: "crate::argument"
        has_default: true
        base_type: "ExtensionObject"
        add_to_type_loader: true
    extra_header: |
      #[allow(unused)]
      mod opcua { pub use crate as types; }
    default_excluded:
      - AnonymousIdentityToken
      - HistoryUpdateType
  - type: nodes
    file: Opc.Ua.NodeSet2.xml
    output_dir: async-opcua-core-namespace/src/generated
    max_nodes_per_file: 100
    extra_header: |
      #[allow(unused)]
      mod opcua { pub use opcua_types as types; pub use opcua_nodes as nodes; }
    types:
      - file: Opc.Ua.Types.xsd
        root_path: opcua::types
    own_namespaces:
      - "http://opcfoundation.org/UA/"
    imported_namespaces: []
    name: CoreNamespace
    events:
      output_dir: async-opcua-core-namespace/src/events
      extra_header: |
        #[allow(unused)]
        mod opcua { pub use opcua_types as types; pub use opcua_nodes as nodes; pub use opcua_nodes::{Event, EventField}; }
        #[allow(unused)]
        use opcua_types as types;
  - type: ids
    file_path: schemas/1.05/NodeIds.csv
    extra_header: |
      mod opcua { pub use crate as types; }
    output_file: async-opcua-types/src/generated/node_ids.rs

sources:
  - schemas/1.05/Opc.Ua.NodeSet2.xml
  - schemas/1.05/Opc.Ua.NodeSet2.Services.xml
  - schemas/1.05/Opc.Ua.Types.xsd
